package org.dairn.storyteller.book

import java.io.BufferedInputStream
import java.io.BufferedOutputStream
import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.Files
import java.nio.file.Path
import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream
import kotlin.io.path.extension
import kotlin.io.path.isRegularFile
import kotlin.io.path.name
import kotlin.streams.asSequence

/** Reader, writer, and deliberately small interoperability validator for DAIRN Book Package v0.1. */
object DairnBookPackage {
    const val PACKAGE_MANIFEST = "dairn-package.yaml"
    const val BOOK_MANIFEST = "book.yaml"
    const val PACKAGE_VERSION = "0.1"

    /** `null` means that the reader must name this hero for the game session. */
    data class BookHero(val id: String, val name: String? = null)

    data class PackageInfo(
        val bookId: String,
        val bookVersion: String,
        val startStory: String,
        val heroes: List<BookHero> = emptyList(),
    )

    fun write(sourceDirectory: Path, destination: Path) {
        require(Files.isDirectory(sourceDirectory)) { "Book source directory does not exist: $sourceDirectory" }
        Files.createDirectories(destination.parent ?: Path.of("."))
        val entries = Files.walk(sourceDirectory).use { paths ->
            paths.asSequence().filter { it.isRegularFile() }.sortedBy { sourceDirectory.relativize(it).toString() }.toList()
        }
        ZipOutputStream(BufferedOutputStream(Files.newOutputStream(destination))).use { zip ->
            writeEntry(zip, PACKAGE_MANIFEST, "package-format: dairn-book-package\npackage-version: \"$PACKAGE_VERSION\"\nbook: $BOOK_MANIFEST\n")
            entries.forEach { file ->
                val name = normalizedPath(sourceDirectory.relativize(file).toString())
                require(name != PACKAGE_MANIFEST) { "Source must not contain $PACKAGE_MANIFEST; it is generated by the packager" }
                zip.putNextEntry(ZipEntry(name).apply { time = 0L })
                Files.newInputStream(file).use { it.copyTo(zip) }
                zip.closeEntry()
            }
        }
    }

    fun read(path: Path): PackageInfo {
        validate(path).throwIfInvalid()
        ZipFile(path.toFile(), UTF_8).use { zip ->
            val book = text(zip, BOOK_MANIFEST)
            return PackageInfo(
                scalar(book, "book-id") ?: error("book.yaml must contain book-id"),
                scalar(book, "book-version") ?: error("book.yaml must contain book-version"),
                scalar(book, "start-story") ?: error("book.yaml must contain start-story"),
                heroes(book),
            )
        }
    }

    data class ValidationResult(val errors: List<String>) {
        val valid get() = errors.isEmpty()
        fun throwIfInvalid() { require(valid) { errors.joinToString("; ") } }
    }

    fun validate(path: Path): ValidationResult {
        val errors = mutableListOf<String>()
        if (path.extension != "dairn") errors += "Package must use the .dairn extension"
        try {
            ZipFile(path.toFile(), UTF_8).use { zip ->
                val names = zip.entries().asSequence().map { it.name }.toList()
                names.forEach { name -> if (!isSafe(name)) errors += "Invalid package path: $name" }
                if (PACKAGE_MANIFEST !in names) errors += "Missing $PACKAGE_MANIFEST"
                if (BOOK_MANIFEST !in names) errors += "Missing $BOOK_MANIFEST"
                if (errors.isNotEmpty()) return ValidationResult(errors)
                val packageManifest = text(zip, PACKAGE_MANIFEST)
                if (scalar(packageManifest, "package-format") != "dairn-book-package") errors += "Unsupported package format"
                if (scalar(packageManifest, "package-version") != PACKAGE_VERSION) errors += "Unsupported package version"
                if (scalar(packageManifest, "book") != BOOK_MANIFEST) errors += "Package manifest must point to book.yaml"
                val book = text(zip, BOOK_MANIFEST)
                val startStory = scalar(book, "start-story")
                if (startStory == null) errors += "book.yaml is missing start-story"
                val stories = listItems(book, "stories", "id", "source")
                if (stories.map { it.first }.size != stories.map { it.first }.toSet().size) errors += "Duplicate story ID"
                val selected = stories.firstOrNull { it.first == startStory }
                if (startStory != null && selected == null) errors += "Missing referenced start story: $startStory"
                stories.forEach { (id, source) ->
                    if (source !in names) errors += "Missing referenced story $id: $source" else validateStory(zip, names.toSet(), source, errors)
                }
                val heroes = heroes(book)
                if (heroes.map { it.id }.size != heroes.map { it.id }.toSet().size) errors += "Duplicate hero ID"
            }
        } catch (e: Exception) {
            errors += "Cannot open package: ${e.message ?: e.javaClass.simpleName}"
        }
        return ValidationResult(errors)
    }

    private fun validateStory(zip: ZipFile, names: Set<String>, source: String, errors: MutableList<String>) {
        val story = text(zip, source)
        val startChapter = scalar(story, "start-chapter")
        if (startChapter == null) errors += "$source is missing start-chapter"
        val chapters = listItems(story, "chapters", "id", "source")
        if (chapters.map { it.first }.size != chapters.map { it.first }.toSet().size) errors += "Duplicate chapter ID in $source"
        if (startChapter != null && chapters.none { it.first == startChapter }) errors += "Missing referenced start chapter: $startChapter"
        chapters.forEach { (_, chapterPath) ->
            val resolved = normalizedPath(Path.of(source).parent.resolve(chapterPath).normalize().toString())
            if (resolved !in names) {
                errors += "Missing referenced chapter: $chapterPath"
            } else {
                validateChapter(zip, resolved, errors)
            }
        }
    }

    private fun validateChapter(zip: ZipFile, chapterPath: String, errors: MutableList<String>) {
        val chapter = text(zip, chapterPath)
        val scenes = Regex("(?m)^#.*?\\{#([^}\\s]+)}\\s*$").findAll(chapter).map { it.groupValues[1] }.toList()
        if (scenes.size != scenes.toSet().size) errors += "Duplicate scene ID in $chapterPath"
        Regex("(?m)^\\s*goto:\\s*([^\\s#]+)\\s*$").findAll(chapter).forEach { match ->
            val target = match.groupValues[1]
            if (target !in scenes) errors += "Invalid goto target in $chapterPath: $target"
        }
    }

    private fun writeEntry(zip: ZipOutputStream, name: String, content: String) {
        zip.putNextEntry(ZipEntry(name).apply { time = 0L })
        zip.write(content.toByteArray(UTF_8))
        zip.closeEntry()
    }

    private fun text(zip: ZipFile, name: String): String = zip.getEntry(name)?.let { entry ->
        BufferedInputStream(zip.getInputStream(entry)).reader(UTF_8).readText()
    } ?: error("Missing $name")

    private fun scalar(yaml: String, key: String): String? = Regex("(?m)^${Regex.escape(key)}:\\s*[\\\"']?([^\\r\\n\\\"']+)[\\\"']?\\s*$")
        .find(yaml)?.groupValues?.get(1)?.trim()

    private fun listItems(yaml: String, list: String, id: String, source: String): List<Pair<String, String>> {
        val block = Regex("(?ms)^${Regex.escape(list)}:\\s*\\n(.*?)(?=^[^ \\t#].*?:|\\z)").find(yaml)?.groupValues?.get(1) ?: return emptyList()
        return Regex("(?ms)^\\s*-\\s*${Regex.escape(id)}:\\s*([^\\r\\n]+)\\s*\\n(.*?)(?=^\\s*-|\\z)").findAll(block).mapNotNull { match ->
            val itemId = match.groupValues[1].trim().trim('"', '\'')
            val itemSource = Regex("(?m)^\\s*${Regex.escape(source)}:\\s*([^\\r\\n]+)").find(match.groupValues[2])?.groupValues?.get(1)?.trim()?.trim('"', '\'')
            itemSource?.let { itemId to it }
        }.toList()
    }

    private fun heroes(yaml: String): List<BookHero> {
        val block = Regex("(?ms)^heroes:\\s*\\n(.*?)(?=^[^ \\t#].*?:|\\z)").find(yaml)?.groupValues?.get(1) ?: return emptyList()
        return Regex("(?ms)^\\s*-\\s*id:\\s*([^\\r\\n]+)\\s*\\n(.*?)(?=^\\s*-|\\z)").findAll(block).map { match ->
            val id = match.groupValues[1].trim().trim('\"', '\'')
            val name = Regex("(?m)^\\s*name:\\s*([^\\r\\n]+)").find(match.groupValues[2])
                ?.groupValues?.get(1)?.trim()?.trim('\"', '\'')?.takeIf { it.isNotBlank() }
            BookHero(id, name)
        }.toList()
    }

    private fun normalizedPath(path: String) = path.replace('\\', '/')
    private fun isSafe(path: String): Boolean {
        val components = path.removeSuffix("/").split('/')
        return path.isNotBlank() && !path.startsWith('/') && components.none { it == ".." || it.isBlank() }
    }
}
